spring:
  application:
    name: spring-validation-configurable

server:
  error:
    include-message: always
    include-binding-errors: always

starship:
  name:
    length:
      min: 3
      max: 20